### ISSUE TITLE
Make buttons scroll with view

### ISSUE THREAD

**Issue by andrewhr** [ricardotda/listview-with-empty-view#1]
A nice small challenge/api toying idea:

The actual code and layout makes two static "sections" on screen. One holding the buttons and another holding the list view, which fills the remaining available space.

When you scrolls, only the portion of the screen where the `ListView` is placed scrolls, keeping the _clear_ and _set_ buttons static. I think that this behavior is better handled with an 'ActionBar', but we always use it so you can try something a little different...

What do you think of trying to make the "control section" (the layout which holds the buttons) to follow the scroll action too? It will be like everything is under a single `ScrollView`.

It's not complicated, but this behavior already bitten us in the past so is nice to know how to use the proper APIs. Hint: you don't need to wrap anything inside _another_ `ScrollView` :wink:

Keep learning! :smiley: :v:

**Comment by ricardotda** [comment]
Thanx for your comments and your suggestion. It will be good for learning this another feature. 

Just one note: when I did this layout, I wanted to keep the first part fixed, because I think this is the best way for the user doesn't miss the control buttons if the list is large. What do you think about it?

But I perfectly agree with you when you suggest to use an `ActionBar` to hold these buttons, once they perform an action.

But I'll think about how to solve this issue, because I'm curious on how to do this. :pensive:
